steps:
- id: 'fetch-git'
  name: 'gcr.io/cloud-builders/git'
  args: ['fetch', '--tags', '--unshallow']

- id: 'clients-python-build'
  name: 'gcr.io/${PROJECT_ID}/olympia/services/auto:stable'
  args: ['/bin/bash', '-c', 'apt-get install -y git python3-venv && python3 -m pip install --upgrade build && python3 -m build']
  dir: 'clients/python'
  waitFor: ['fetch-git']

- id: 'clients-python-publish'
  name: 'gcr.io/${PROJECT_ID}/olympia/services/auto:stable'
  args: ['/bin/bash', '-c', 'if [[ "${TAG_NAME}" != clients-python-* ]]; then echo "Skipping publishing client"; exit 0; fi; python3 -m pip install twine --upgrade; twine upload dist/*']
  dir: 'clients/python'
  env:
  - "TWINE_USERNAME=__token__"
  - "TWINE_PASSWORD=pypi-${_PYPI_AUTH_TOKEN}"
  waitFor: ['clients-python-build']
