theme: null
markdown: kramdown

toc:
  min_level: 2
  max_level: 3

title: Sust Global Developer Center

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
- jekyll-toc

keep_files:
- py
