services:
  app:
    build:
      context: ..
      dockerfile: ./hack/Dockerfile
    command: ["/bin/bash", "-xec", "cd jekyll && bundle install && bundle exec jekyll serve --force_polling -H 0.0.0.0 -P 4000"]
    ports:
      - "4000:4000"
    volumes:
      - ../../:/app